name: .\venv
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - expat=2.6.3=h5da7b33_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.15=h827c3e9_0
  - pip=24.2=py312haa95532_0
  - python=3.12.4=h14ffc60_1
  - setuptools=75.1.0=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - tzdata=2024a=h04d1e81_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - wheel=0.44.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - blinker==1.8.2
      - click==8.1.7
      - flask==3.0.3
      - flask-mail==0.10.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - werkzeug==3.0.4
prefix: .\venv
